### ISSUE TITLE
TypeError or ImportError when using

### ISSUE THREAD

**Issue by TomaOC** [ebranlard/matlab2python#13]
Dear ebranlard,

I successfully downloaded and installed matlab2python, but when I try to use it I get the following errors:
`python matlab2python.py file.m `
gives
`TypeError: 'errors' is an invalid keyword argument for this function`
while
`python3 matlab2python.py file.m `
gives
`ImportError: cannot import name 'cached_property' from 'functools' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/functools.py)`

Any ideas?

Thanks in advance!

**Comment by ebranlard** [comment]
Hi @TomaOC 

matlab2python is now for python3 only, so it's expected that it will fail with python 2. 

Your error with python 3.7 is a bit more of a mystery. The code should work with python 3.7, 3.8 and 3.9, which is what we use for the continuous integration tests (on windows and linux, I'll add MacOS now). 

Does the code run on a simpler file? 
```python matlab2python.py .\tests\files\fSpectrum.m```

Can you maybe post the full error message you get with your python3? 

It might be that your issue is related to the mac version of python 3.7, I'm really not sure. A quick look for the error `ImportError: cannot import name 'cached_property' from 'functools'` on the web seem to indicate that the easiest way to resolve this is to use version 3.8. 

Keep me in touch!

**Comment by ebranlard** [comment]
I've updated the test matrix (https://github.com/ebranlard/matlab2python/runs/8067090265?check_suite_focus=true) and there doesn't seem to be any issue when running on github actions. 

Have you installed the requirements? 
`python3 -m pip install -r requirements.txt`

**Comment by TomaOC** [comment]
Hi @ebranlard 

Thank you for responding so quickly! The solution turned out to be a combination of your suggestions:
After upgrading the latest version of Python (3.10) and reinstalling the requirements, matlab2python appears to work!
Just to be sure, this is the result of converting the test file `fSpectrum.m`
`
import numpy as np
    
def fSpectrum(y = None,N = None,fs = None): 
    y = np.transpose(y)
    vf = (np.arange(0,N / 2+1)) * fs / N
    vf = (np.arange(0,int(np.floor(N / 2))+1)) * fs / N
    Sp = np.abs(np.fft.rfft(y)) ** 2 / (N * fs)
    Sp = Sp(np.arange(1,int(np.floor(N / 2)) + 1+1))
    return Sp,vf
`
Does that look about right to you?

Thanks again!

**Comment by ebranlard** [comment]
Hi @TomaOC 
I'm glad things are now working. 

Yes the output is correct. Currently the code does not handle variable indices correctly and requires manual editing. 

I'll close the issue, feel free to open a new one (though I haven't actively developed on this project for a while). 
Cheers,
